apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
      - name: app
        image: ghcr.io/barbaricat/pipechallenge:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /items
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
spec:
#  type: LoadBalancer
  type: NodePort
  selector:
    app: nestjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31001
