name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # не учитываем старые коммиты для ускорения

      # эмулятор арм процессора для образа под него
      # - name: Set up QEMU
      #  if: matrix.platform == 'linux/arm64'
      #  uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub CR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }} # две сборки парралельно
          push: true
          # Чтобы не было лишнего мусора используем ${{ github.event_name != 'pull_request' }}, но Тру для скорости.
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
            ${{ matrix.platform == 'linux/amd64' && format('ghcr.io/{0}:latest', github.repository) || '' }}
          # не использовал мердж манифест во благо скорости (лэйтест только амд);
          # || - для false условия, format для разрешения +

          cache-from: type=gha
          cache-to: type=gha,mode=max


